Plotter_settings:
  Output: 'output/plots/sarsa'
  Width: 3840
  Height: 1080
  Metrics: ['system_total_stopped','system_total_waiting_time','system_mean_waiting_time','system_mean_speed']

Agent_settings:
  Output: 'output/csv/sarsa'
  Traffic_type: 'medium'
  Instances:
    SARSA_run_1:
      Agent_type: 'SARSA'
      Runs: 5
      Alpha: 0.0001
      Gamma: 0.99
      Epsilon: 0.05
      FourierOrder: 7
      Lambda: 0.9
    SARSA_run_2:
      Agent_type: 'SARSA'
      Runs: 5
      Alpha: 0.001
      Gamma: 0.9
      Epsilon: 0.1
      FourierOrder: 7
      Lambda: 0.99
