Plotter_settings:
  Output: 'output/plots/sarsa'
  Width: 3840
  Height: 1080
  Metrics: ['system_total_stopped','system_total_waiting_time','system_mean_waiting_time','system_mean_speed']

Agent_settings:
  Output: 'output/csv/sarsa'
  Environment:
    Traffic_type: 'low'
    Gui: False
    Num_seconds: 10000
    Min_green: 5
    Max_green: 50
    Yellow_time: 2
    Delta_time: 5
  Instances:
    SARSA_run_1:
      Agent_type: 'SARSA'
      Runs: 1
      Alpha: 0.00005
      Gamma: 0.9
      Epsilon: 0.1
      FourierOrder: 12
      Lambda: 0.999
    SARSA_run_2:
      Agent_type: 'SARSA'
      Runs: 1
      Alpha: 0.00001
      Gamma: 0.9
      Epsilon: 0.01
      FourierOrder: 10
      Lambda: 0.999
    SARSA_run_3:
      Agent_type: 'SARSA'
      Runs: 1
      Alpha: 0.00001
      Gamma: 0.75
      Epsilon: 0.01
      FourierOrder: 12
      Lambda: 0.999
    SARSA_run_4:
      Agent_type: 'SARSA'
      Runs: 1
      Alpha: 0.00001
      Gamma: 0.75
      Epsilon: 0.01
      FourierOrder: 10
      Lambda: 0.999





