Plotter_settings:
  Output: 'output/plots/sarsa'
  Width: 3840
  Height: 1080
  Metrics: ['system_total_stopped','system_total_waiting_time','system_mean_waiting_time','system_mean_speed']

Agent_settings:
  Output: 'output/csv/sarsa'
  Environment:
    Traffic_type: 'low'
    Gui: False
    Num_seconds: 10000
    Min_green: 5
    Max_green: 50
    Yellow_time: 2
    Delta_time: 5
  Instances:
    SARSA_run_1:
      Agent_type: 'SARSA'
      Runs: 2
      Alpha: 0.0001
      Gamma: 0.99
      Epsilon: 0.05
      FourierOrder: 7
      Lambda: 0.9
    SARSA_run_2:
      Agent_type: 'SARSA'
      Runs: 2
      Alpha: 0.001
      Gamma: 0.9
      Epsilon: 0.1
      FourierOrder: 7
      Lambda: 0.99
