Plotter_settings:
  Output: 'output/plots/ql'
  Width: 3840
  Height: 1080
  Metrics: ['system_total_stopped','system_total_waiting_time','system_mean_waiting_time','system_mean_speed']

Agent_settings:
  Output: 'output/csv/ql'
  Traffic_type: 'high'
  Instances:
    QL_run_1:
      Agent_type: 'QL'
      Runs: 5
      Alpha: 0.1
      Gamma: 0.99
      Init_epsilon: 1.0
      Min_epsilon: 0.01
      Decay: 0.99
    QL_run_2:
      Agent_type: 'QL'
      Runs: 5
      Alpha: 0.4
      Gamma: 0.5
      Init_epsilon: 1.0
      Min_epsilon: 0.01
      Decay: 0.9995

