Plotter_settings:
  Output: 'output/plots/fixed'
  Width: 3840
  Height: 1080
  Metrics: ['system_total_stopped','system_total_waiting_time','system_mean_waiting_time','system_mean_speed']

Agent_settings:
  Output: 'output/csv/fixed'
  Environment:
    Traffic_type: 'low'
    Gui: False
    Num_seconds: 10000
    Min_green: 5
    Max_green: 50
    Yellow_time: 2
    Delta_time: 5
  Instances:
    Fixed_run:
      Agent_type: 'FIXED'
      Runs: 1