Plotter_settings:
  Output: 'output/plots/fixed'
  Width: 3840
  Height: 1080
  Metrics: ['system_total_stopped','system_total_waiting_time','system_mean_waiting_time','system_mean_speed']

Agent_settings:
  Output: 'output/csv/fixed'
  Traffic_type: 'low'
  Instances:
    Fixed_run:
      Agent_type: 'FIXED'
      Runs: 1