Agent_settings:
  Instances:
    QL_run_1:
      Alpha: 0.01083
      Decay: 0.96211
      Gamma: 0.95794
      Metrics:
        system_mean_speed: 5.931084149071421
        system_mean_waiting_time: -21.38011897319314
        system_total_stopped: -9.6
        system_total_waiting_time: -509.6
    QL_run_10:
      Alpha: 0.04843
      Decay: 0.92937
      Gamma: 0.89396
      Metrics:
        system_mean_speed: 6.294152015140119
        system_mean_waiting_time: -37.84288126112383
        system_total_stopped: -9.2
        system_total_waiting_time: -940.3
    QL_run_2:
      Alpha: 0.06466
      Decay: 0.95341
      Gamma: 0.91242
      Metrics:
        system_mean_speed: 7.266663114780924
        system_mean_waiting_time: -11.017390238704177
        system_total_stopped: -6.4
        system_total_waiting_time: -226.0
    QL_run_3:
      Alpha: 0.0054
      Decay: 0.9442
      Gamma: 0.89351
      Metrics:
        system_mean_speed: 7.752413515303537
        system_mean_waiting_time: -20.71011157796452
        system_total_stopped: -7.6
        system_total_waiting_time: -550.6
    QL_run_4:
      Alpha: 0.05357
      Decay: 0.94835
      Gamma: 0.94457
      Metrics:
        system_mean_speed: 7.093222294913538
        system_mean_waiting_time: -16.603721542548918
        system_total_stopped: -8.3
        system_total_waiting_time: -439.3
    QL_run_5:
      Alpha: 0.08687
      Decay: 0.97676
      Gamma: 0.95332
      Metrics:
        system_mean_speed: 7.690935878795932
        system_mean_waiting_time: -14.381634557990727
        system_total_stopped: -6.3
        system_total_waiting_time: -307.4
    QL_run_6:
      Alpha: 0.08504
      Decay: 0.94937
      Gamma: 0.98992
      Metrics:
        system_mean_speed: 6.72102700992833
        system_mean_waiting_time: -26.842709725632538
        system_total_stopped: -9.3
        system_total_waiting_time: -665.7
    QL_run_7:
      Alpha: 0.01617
      Decay: 0.9331
      Gamma: 0.99439
      Metrics:
        system_mean_speed: 5.915527268325759
        system_mean_waiting_time: -22.32456611375529
        system_total_stopped: -10.0
        system_total_waiting_time: -536.7
    QL_run_8:
      Alpha: 0.04663
      Decay: 0.94588
      Gamma: 0.80032
      Metrics:
        system_mean_speed: 6.712018388921967
        system_mean_waiting_time: -21.49271469113961
        system_total_stopped: -9.1
        system_total_waiting_time: -498.2
    QL_run_9:
      Alpha: 0.06109
      Decay: 0.98312
      Gamma: 0.8012
      Metrics:
        system_mean_speed: 7.187626742490903
        system_mean_waiting_time: -27.606523739567223
        system_total_stopped: -9.6
        system_total_waiting_time: -701.9
  Traffic_type_training:
  - low
  - medium
  - high
Plotter_settings:
  Height: 1080
  Metrics:
  - system_total_stopped
  - system_total_waiting_time
  - system_mean_waiting_time
  - system_mean_speed
  Output: output/plots/ql
  Width: 3840
