Plotter_settings:
  Output: 'output/plots/test_low'
  Width: 3840
  Height: 1080
  Metrics: ['system_total_stopped','system_total_waiting_time','system_mean_waiting_time','system_mean_speed']

Agent_settings:
  Output_csv: 'output/csv/ql'
  Output_model: 'output/models'
  Environment:
    Traffic_type: 'low'
    Gui: False
    Num_seconds: 10000
    Min_green: 5
    Max_green: 50
    Yellow_time: 2
    Delta_time: 5
  Instances:
    QL_run_1:
      Agent_type: 'QL'
      Runs: 2
      Alpha: 0.1
      Gamma: 0.99
      Init_epsilon: 1.0
      Min_epsilon: 0.01
      Decay: 0.99
    QL_run_2:
      Agent_type: 'QL'
      Runs: 2
      Alpha: 0.01
      Gamma: 0.75
      Init_epsilon: 1.0
      Min_epsilon: 0.01
      Decay: 0.9995

