Plotter_settings:
  Output: 'output/plots/learning_low'
  Width: 3840
  Height: 1080
  Metrics: ['system_total_stopped','system_total_waiting_time','system_mean_waiting_time','system_mean_speed']

Agent_settings:
  Output_csv: 'output/csv/learning'
  Output_model: 'output/models/learning_low'
  Environment:
    Traffic_type: 'low'
    Gui: False
    Num_seconds: 100000
    Min_green: 5
    Max_green: 50
    Yellow_time: 2
    Delta_time: 5
  Instances:
    Fixed_run:
      Agent_type: 'FIXED'
      Runs: 1
    QL_run_1:
      Agent_type: 'QL'
      Runs: 5
      Alpha: 0.3
      Gamma: 0.75
      Init_epsilon: 1.0
      Min_epsilon: 0.1
      Decay: 0.8
    QL_run_2:
      Agent_type: 'QL'
      Runs: 5
      Alpha: 0.35
      Gamma: 0.8
      Init_epsilon: 1.0
      Min_epsilon: 0.1
      Decay: 0.8
    DQN_run_1:
      Agent_type: 'DQN'
      Runs: 5
      Alpha: 0.01
      Gamma: 0.75
      Init_epsilon: 1.0
      Final_epsilon: 0.01
      Exp_fraction: 0.9
    DQN_run_2:
      Agent_type: 'DQN'
      Runs: 5
      Alpha: 0.01
      Gamma: 0.8
      Init_epsilon: 1.0
      Final_epsilon: 0.01
      Exp_fraction: 0.99
    SARSA_run_1:
      Agent_type: 'SARSA'
      Runs: 5
      Alpha: 0.00005
      Gamma: 0.9
      Epsilon: 0.01
      FourierOrder: 7
      Lambda: 0.999
    SARSA_decay_run_1:
      Agent_type: 'SARSA_decay'
      Runs: 5
      Alpha: 0.00005
      Gamma: 0.9
      Epsilon: 0.01
      Decay: 0.99
      FourierOrder: 7
      Lambda: 0.999


