Plotter_settings:
  Output: 'output/plots/ql'
  Width: 3840
  Height: 1080
  Metrics: ['system_total_stopped','system_total_waiting_time','system_mean_waiting_time','system_mean_speed']

Agent_settings:
  Output: 'output/csv/test'
  Traffic_type: 'low'
  Instances:
    QL_run_2:
      Agent_type: 'QL'
      Runs: 5
      Alpha: 0.001
      Gamma: 0.9
      Init_epsilon: 1.0
      Min_epsilon: 0.01
      Decay: 0.9995
    DQN_run_2:
      Agent_type: 'DQN'
      Runs: 5
      Alpha: 0.001
      Gamma: 0.9
      Init_epsilon: 1.0
      Final_epsilon: 0.01
      Exp_fraction: 0.9996
    SARSA_run_1:
      Agent_type: 'SARSA'
      Runs: 5
      Alpha: 0.0001
      Gamma: 0.99
      Epsilon: 0.05
      FourierOrder: 7
      Lambda: 0.9
