Plotter_settings:
  Output: 'output/plots/test_plotter'
  Width: 3840
  Height: 1080
  Metrics: ['system_total_stopped','system_total_waiting_time','system_mean_waiting_time','system_mean_speed']

Agent_settings:
  Output_csv: 'output/csv/test'
  Output_model : 'output/models'
  Environment:
    Traffic_type: 'low'
    Gui: False
    Num_seconds: 100
    Min_green: 5
    Max_green: 50
    Yellow_time: 2
    Delta_time: 5
  Instances:
    Fixed_run:
      Agent_type: 'FIXED'
      Runs: 1
    QL_run:
      Agent_type: 'QL'
      Runs: 5
      Model: 'output/models/QL_run.pkl'
    DQN_run:
      Agent_type: 'DQN'
      Runs: 5
      Alpha: 0.001
      Gamma: 0.9
      Init_epsilon: 1.0
      Final_epsilon: 0.01
      Exp_fraction: 0.9996
