Plotter_settings:
  Output: 'output/plots/test_high_high'
  Width: 3840
  Height: 1080
  Metrics: ['system_total_stopped','system_total_waiting_time','system_mean_waiting_time','system_mean_speed']

Agent_settings:
  Output_csv: 'output/csv/test_high_high'
  Output_model: 'output/models/test_high_high'
  Environment:
    Traffic_type: 'high'
    Gui: False
    Num_seconds: 20000
    Min_green: 5
    Max_green: 50
    Yellow_time: 2
    Delta_time: 5
  Instances:
    Fixed_run:
      Agent_type: 'FIXED'
      Runs: 1
    QL_run_1:
      Agent_type: 'QL'
      Runs: 1
      Model: 'output/models/learning_high/QL_run_1.pkl'
    QL_run_2:
      Agent_type: 'QL'
      Runs: 1
      Model: 'output/models/learning_high/QL_run_2.pkl'
    DQN_run_1:
      Agent_type: 'DQN'
      Runs: 1
      Model: 'output/models/learning_high/DQN_run_1.pkl'
    DQN_run_2:
      Agent_type: 'DQN'
      Runs: 1
      Model: 'output/models/learning_high/DQN_run_2.pkl'
    SARSA_run_1:
      Agent_type: 'SARSA'
      Runs: 1
      Model: 'output/models/learning_high/SARSA_run_1.pkl'
    SARSA_decay_run_1:
      Agent_type: 'SARSA_decay'
      Runs: 1
      Model: 'output/models/learning_high/SARSA_decay_run_1.pkl'
